spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost:27017}/candidates?serverSelectionTimeoutMS=2000&connectTimeoutMS=2000
server:
  port: 8081
app:
  queue:
    candidate:
      candidate-code-queue: candidate.code.local